import Image from "next/image";
// import Footer from '../components/Footer'
import Navbar from "../../components/Navbar";
import Page from "./page";
import "../../globals.css";
// import { Handjet } from 'next/font/google'

const inter = { subsets: ["latin"] };

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
      </body>
    </html>
  );
}
